export const GLOSSARY = [
  { term:'ROI', cat:'Métricas', def:'Return on Investment — Retorno sobre Investimento. (Lucro - Investimento) / Investimento.' },
  { term:'ROIC', cat:'Métricas', def:'Return on Invested Capital — Eficiência da empresa em gerar lucro a partir do capital total empregado.' },
  { term:'CAC', cat:'Métricas', def:'Customer Acquisition Cost — Custo de aquisição de um novo cliente.' },
  { term:'LTV', cat:'Métricas', def:'Lifetime Value — Receita total esperada de um cliente durante todo o relacionamento.' },
  { term:'LTV/CAC', cat:'Métricas', def:'Razão LTV/CAC. Saudável a partir de 3:1.' },
  { term:'Payback', cat:'Métricas', def:'Tempo para recuperar o investimento via lucro gerado.' },
  { term:'Margem Bruta', cat:'Métricas', def:'(Receita - Custo Variável) / Receita.' },
  { term:'Margem Líquida', cat:'Métricas', def:'Lucro Líquido / Receita.' },
  { term:'EBITDA', cat:'Métricas', def:'Lucro antes de juros, impostos, depreciação e amortização.' },
  { term:'Burn Rate', cat:'Métricas', def:'Velocidade com que o caixa é consumido por mês.' },
  { term:'Runway', cat:'Métricas', def:'Quantos meses o caixa atual cobre as despesas. Caixa / Burn Rate.' },
  { term:'CDI', cat:'Renda Fixa', def:'Certificado de Depósito Interbancário — referência para investimentos de renda fixa BR.' },
  { term:'Selic', cat:'Renda Fixa', def:'Taxa básica de juros da economia BR definida pelo Copom.' },
  { term:'IPCA', cat:'Renda Fixa', def:'Índice de Preços ao Consumidor Amplo — inflação oficial do Brasil (IBGE).' },
  { term:'IPCA+', cat:'Renda Fixa', def:'Tesouro IPCA+ — paga inflação + taxa fixa. Protege poder de compra.' },
  { term:'Marcação a Mercado', cat:'Renda Fixa', def:'Reavaliação diária do preço do título conforme condições atuais.' },
  { term:'FGC', cat:'Renda Fixa', def:'Fundo Garantidor de Créditos — protege CDBs, LCIs, LCAs até R$ 250k por CPF/CNPJ/instituição.' },
  { term:'Dividend Yield (DY)', cat:'Renda Variável', def:'Dividendo anual / Preço da ação.' },
  { term:'P/L', cat:'Renda Variável', def:'Preço sobre Lucro — anos de lucro atual para recuperar o investimento.' },
  { term:'P/VP', cat:'Renda Variável', def:'Preço sobre Valor Patrimonial.' },
  { term:'ROE', cat:'Renda Variável', def:'Return on Equity — Lucro Líquido / Patrimônio Líquido.' },
  { term:'CAGR', cat:'Renda Variável', def:'Taxa de crescimento anual composta.' },
  { term:'Drawdown', cat:'Risco', def:'Maior queda percentual sofrida do pico ao vale.' },
  { term:'Volatilidade', cat:'Risco', def:'Medida estatística da variação dos retornos.' },
  { term:'Sharpe Ratio', cat:'Risco', def:'Retorno excedente por unidade de risco. Acima de 1 é bom.' },
  { term:'Hedge', cat:'Risco', def:'Estratégia de proteção contra riscos.' },
  { term:'Liquidez', cat:'Risco', def:'Facilidade de converter um ativo em dinheiro sem perda significativa.' },
  { term:'Asset Allocation', cat:'Estratégia', def:'Distribuição estratégica do patrimônio entre classes de ativos.' },
  { term:'Rebalanceamento', cat:'Estratégia', def:'Ajuste periódico da carteira para manter a proporção desejada.' },
  { term:'Buy & Hold', cat:'Estratégia', def:'Comprar e manter por longo prazo.' },
  { term:'IR Regressivo', cat:'Tributação', def:'22.5% (até 180d) → 20% → 17.5% → 15% (>720d).' },
  { term:'Come-cotas', cat:'Tributação', def:'Antecipação semestral de IR em fundos (maio/novembro).' },
  { term:'DARF', cat:'Tributação', def:'Documento de Arrecadação de Receitas Federais.' },
  { term:'DAS', cat:'Tributação', def:'Documento de Arrecadação do Simples Nacional.' },
  { term:'Lucro Real', cat:'Tributação', def:'Regime tributário PJ baseado no lucro contábil ajustado.' },
  { term:'Lucro Presumido', cat:'Tributação', def:'Regime PJ com base de cálculo presumida sobre faturamento.' },
  { term:'Simples Nacional', cat:'Tributação', def:'Regime simplificado PJ com tributos unificados em DAS.' },
  { term:'IRPJ', cat:'Tributação', def:'Imposto de Renda Pessoa Jurídica — 15% + adicional 10%.' },
  { term:'CSLL', cat:'Tributação', def:'Contribuição Social sobre o Lucro Líquido — 9%.' },
  { term:'PIS / COFINS', cat:'Tributação', def:'Contribuições sobre faturamento. Regime cumulativo (0,65%/3%) ou não-cumulativo (1,65%/7,6%).' },
  { term:'INSS Patronal', cat:'Folha', def:'20% do salário (Lucro Real/Presumido). No Simples já incluso no DAS.' },
  { term:'FGTS', cat:'Folha', def:'8% do salário depositado mensalmente em conta vinculada do empregado.' },
  { term:'IRRF', cat:'Folha', def:'Imposto de Renda Retido na Fonte sobre a folha de salário.' },
  { term:'CFOP', cat:'NF', def:'Código Fiscal de Operações e Prestações.' },
  { term:'NCM', cat:'NF', def:'Nomenclatura Comum do Mercosul — classifica mercadorias.' },
  { term:'Holding', cat:'Estrutura', def:'Sociedade que detém participação em outras empresas ou patrimônio.' },
];
